name: Unit Tests

on: [push]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # - name: Setup Node.js environment
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14' # Specify the Node.js version you want to use.

      - name: Install dependencies
        run: yarn install --frozen-lockfile # Use frozen-lockfile to ensure reproducibility.

      - name: Run Tests
        run: yarn test