name: Unit Tests

on: [push]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile # Use frozen-lockfile to ensure reproducibility.

      - name: Run Tests
        run: yarn test
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: yarn build
          start: yarn start