name: Unit Tests

on: [push]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile # Use frozen-lockfile to ensure reproducibility.

      - name: Run Tests
        run: yarn test